export type DashboardTourStep = {
  id: string;
  group: string;
  href: string;
  /** data-tour attribute to spotlight. Omit for a centered card with no highlight. */
  target?: string;
  emoji: string;
  title: string;
  description: string;
  bullets: string[];
};

export const DASHBOARD_TOUR_STEPS: DashboardTourStep[] = [
  {
    id: "welcome",
    group: "Getting started",
    href: "/dashboard",
    target: "tour-overview-hero",
    emoji: "👋",
    title: "Welcome to cried.bio",
    description:
      "This tour walks you through the full dashboard — not just the sidebar. We will open each area and show you what to use it for.",
    bullets: [
      "Your public page lives at cried.bio/yourname once you publish.",
      "Everything in the dashboard saves separately — profile, look, content, and stats.",
      "Use Next to follow along; we will navigate for you.",
    ],
  },
  {
    id: "overview-stats",
    group: "Getting started",
    href: "/dashboard",
    target: "tour-overview-stats",
    emoji: "📊",
    title: "Your numbers at a glance",
    description: "The overview shows live stats so you always know how your page is performing.",
    bullets: [
      "Views counts every time someone loads your profile.",
      "Visitors tracks unique people — useful for reach, not just refreshes.",
      "Clicks totals link taps across your page.",
      "Links shows how many buttons you have published.",
    ],
  },
  {
    id: "overview-search",
    group: "Getting started",
    href: "/dashboard",
    target: "tour-overview-search",
    emoji: "🔍",
    title: "Search anything in the dashboard",
    description: "cried.bio has dozens of settings. Search is the fastest way to find them.",
    bullets: [
      "Press ⌘K (Mac) or Ctrl+K (Windows) from anywhere in the dashboard.",
      "Search by page name, feature, or keyword — e.g. “cursor”, “background”, “badges”.",
      "Great when you remember what you want but not where it lives.",
    ],
  },
  {
    id: "nav-sidebar",
    group: "Getting started",
    href: "/dashboard",
    target: "profile",
    emoji: "🧭",
    title: "How the sidebar is organized",
    description: "The left sidebar groups cried.bio into sections. Most sections open a hub with sub-pages.",
    bullets: [
      "Profile — who you are (name, bio, avatar, banner).",
      "Appearance — colors, background, layouts, effects, custom CSS.",
      "Content — links, embeds, widgets, and music.",
      "Community, Explore, Stats, Premium, and Settings — each covered in this tour.",
    ],
  },
  {
    id: "profile-identity",
    group: "Profile",
    href: "/dashboard/profile",
    target: "tour-profile-identity",
    emoji: "👤",
    title: "Profile — your public identity",
    description: "This is what people see first: your username, display name, bio, and location.",
    bullets: [
      "Username sets your URL — cried.bio/yourname (changeable once every 7 days).",
      "Display name is the big title on your page; it can include spaces and emoji.",
      "Bio supports styled text — configure colors and effects under Appearance later.",
      "Location appears next to your view count when filled in.",
    ],
  },
  {
    id: "profile-media",
    group: "Profile",
    href: "/dashboard/profile",
    target: "tour-profile-media",
    emoji: "🖼️",
    title: "Avatar & banner uploads",
    description: "Upload a profile picture and header banner. Both support crop and reposition before saving.",
    bullets: [
      "Avatar appears in layouts and next to your name.",
      "Banner shows on layouts that include a header image.",
      "GIFs upload as-is; still images open a crop dialog.",
      "Remove either image anytime with the remove button.",
    ],
  },
  {
    id: "appearance-hub",
    group: "Appearance",
    href: "/dashboard/appearance",
    target: "tour-hub-appearance",
    emoji: "🎨",
    title: "Appearance hub",
    description: "Everything about how your page looks lives under Appearance — not just one page.",
    bullets: [
      "Customize — fonts, colors, card glass, opacity, alignment.",
      "Background — solid, gradient, image, video, particles.",
      "Layouts — 37+ profile structures, including premium animated ones.",
      "Effects — cursor, favicon, enter gate, page entrance, username effects.",
      "Custom Themes — write scoped CSS when you want full control.",
    ],
  },
  {
    id: "customize",
    group: "Appearance",
    href: "/dashboard/customize",
    target: "tour-customize",
    emoji: "🎛️",
    title: "Customize — core styling",
    description: "Set accent and text colors, pick a font, and tune how your profile card renders.",
    bullets: [
      "Accent color drives buttons, highlights, and many effects.",
      "Font choice applies to your whole public page.",
      "Card opacity, blur, and glassmorphism control the frosted-glass look.",
      "Toggle view count, join date, neon glow, and content alignment here.",
      "Live preview on the right (desktop) shows changes instantly.",
    ],
  },
  {
    id: "background",
    group: "Appearance",
    href: "/dashboard/background",
    target: "tour-background",
    emoji: "🌌",
    title: "Background",
    description: "Your backdrop sits behind the profile card — it sets the whole mood of the page.",
    bullets: [
      "Pick solid color, animated gradient, uploaded image, or video.",
      "Particle effects add snow, stars, rain, and more on top.",
      "Overlay opacity darkens busy backgrounds so text stays readable.",
      "Premium unlocks additional particle types and video backgrounds.",
    ],
  },
  {
    id: "layouts",
    group: "Appearance",
    href: "/dashboard/themes",
    target: "tour-layouts",
    emoji: "📐",
    title: "Layouts",
    description: "Layouts completely change how your profile is structured — not just colors.",
    bullets: [
      "Standard layouts are free — Classic, Minimal, Hero, and many more.",
      "Premium Lite unlocks exclusive layouts with animations (matrix, liquid, supernova…).",
      "Each layout positions avatar, name, links, and widgets differently.",
      "Pick “Custom” to attach a community or personal CSS theme.",
    ],
  },
  {
    id: "effects",
    group: "Appearance",
    href: "/dashboard/effects",
    target: "tour-effects",
    emoji: "✨",
    title: "Effects",
    description: "Polish details visitors notice: cursor, browser tab, username animation, and enter screen.",
    bullets: [
      "Custom cursor and favicon brand your tab and pointer.",
      "Tab title animations cycle text in the browser tab.",
      "Username effects add glow, rainbow, shimmer, shadow, and more.",
      "Enter gate shows a click-to-enter screen before your page loads.",
      "Page entrance animates the card when visitors arrive.",
    ],
  },
  {
    id: "content-hub",
    group: "Content",
    href: "/dashboard/content",
    target: "tour-hub-content",
    emoji: "🔗",
    title: "Content hub",
    description: "What visitors interact with — links, media embeds, live widgets, and music.",
    bullets: [
      "Links — unlimited buttons with icons, colors, and animations.",
      "Embeds — YouTube, Spotify, Twitch, Roblox, and more.",
      "Widgets — Discord live status and other live blocks.",
      "Music — background player with playlists (Premium for multiple tracks).",
    ],
  },
  {
    id: "links",
    group: "Content",
    href: "/dashboard/links",
    target: "tour-links",
    emoji: "🔗",
    title: "Links",
    description: "Your link buttons are the main call-to-actions on most profiles.",
    bullets: [
      "Drag and drop to reorder — order is exactly what visitors see.",
      "Each link can have its own icon, color, glow, and open animation.",
      "Featured links can be styled differently to stand out.",
      "Track clicks per link in Stats → Analytics.",
    ],
  },
  {
    id: "embeds",
    group: "Content",
    href: "/dashboard/embeds",
    target: "tour-embeds",
    emoji: "📺",
    title: "Embeds",
    description: "Paste a URL and cried.bio renders rich cards for supported platforms.",
    bullets: [
      "YouTube, Twitch, Spotify, SoundCloud, Roblox, and more.",
      "Expand each embed to customize title, size, and display style.",
      "Embeds appear in your profile content sections alongside links.",
    ],
  },
  {
    id: "widgets",
    group: "Content",
    href: "/dashboard/widgets",
    target: "tour-widgets",
    emoji: "🧩",
    title: "Widgets",
    description: "Connect external services that update live on your profile.",
    bullets: [
      "Connect Discord to show what you are playing or your online status.",
      "Requires joining Lanyard so Discord activity can sync.",
      "Toggle visibility without disconnecting your account.",
    ],
  },
  {
    id: "music",
    group: "Content",
    href: "/dashboard/music",
    target: "tour-music",
    emoji: "🎵",
    title: "Music player",
    description: "Add background audio that plays when visitors open your profile.",
    bullets: [
      "Upload tracks or link external audio depending on your plan.",
      "Configure autoplay, volume, and player color in the settings below.",
      "Premium unlocks playlists with multiple tracks.",
    ],
  },
  {
    id: "community-hub",
    group: "Community",
    href: "/dashboard/community",
    target: "tour-hub-community",
    emoji: "💬",
    title: "Community",
    description: "Tools for audience engagement beyond static links.",
    bullets: [
      "Guestbook — visitors leave messages and reactions on your page.",
      "Followers — see who follows you and manage friends.",
      "Badges — display achievements and store-bought badge flair.",
      "Featured — pin highlight blocks above your links.",
    ],
  },
  {
    id: "explore-hub",
    group: "Explore",
    href: "/dashboard/explore",
    target: "tour-hub-explore",
    emoji: "🌎",
    title: "Explore",
    description: "Discover other creators and install looks from the community.",
    bullets: [
      "Explore Profiles — browse cried.bio users and suggested creators.",
      "Community Themes — install CSS themes shared by others.",
      "Leaderboard — top profiles by views and followers.",
    ],
  },
  {
    id: "presets-hub",
    group: "Presets",
    href: "/dashboard/presets",
    target: "tour-hub-presets",
    emoji: "💾",
    title: "Presets — save entire looks",
    description: "A preset captures your full profile style so you can switch scenes instantly.",
    bullets: [
      "My presets — save your current colors, layout, background, and more.",
      "Community presets — browse looks shared by other users.",
      "Scheduled presets (Premium) auto-swap between day/night styles.",
    ],
  },
  {
    id: "analytics",
    group: "Stats",
    href: "/dashboard/analytics",
    target: "tour-analytics",
    emoji: "📈",
    title: "Analytics",
    description: "Deep dive into traffic over the last 30 days.",
    bullets: [
      "Daily view and click charts show trends over time.",
      "See which links get the most clicks.",
      "Country breakdown shows where visitors come from.",
      "Premium unlocks advanced analytics and longer history.",
    ],
  },
  {
    id: "premium",
    group: "Premium",
    href: "/dashboard/premium/plans",
    target: "tour-premium",
    emoji: "⭐",
    title: "Premium & extras",
    description: "Upgrade for playlists, extra pages, premium layouts, fonts, and more.",
    bullets: [
      "Premium Lite — layouts, fonts, particles, playlists, analytics.",
      "Store — one-time badge packs, gifts, and cosmetics.",
      "Pages — build extra content pages on your personal site (Premium).",
      "Custom effect — request a bespoke profile effect (Premium).",
    ],
  },
  {
    id: "settings",
    group: "Settings",
    href: "/dashboard/settings",
    target: "tour-settings",
    emoji: "⚙️",
    title: "Settings",
    description: "Account security, billing, privacy, and dashboard preferences.",
    bullets: [
      "Change email, password, and username (with cooldown).",
      "View purchase history and manage Premium billing.",
      "Restart this dashboard tour anytime from Settings → Account.",
    ],
  },
  {
    id: "finish",
    group: "Finish",
    href: "/dashboard",
    emoji: "🚀",
    title: "You are ready to build",
    description: "That covers the full cried.bio dashboard. Start with Profile and Customize, then add links.",
    bullets: [
      "Open your live page from the overview or sidebar anytime.",
      "Use ⌘K / Ctrl+K whenever you are lost.",
      "Join the Discord community if you want inspiration or help.",
      "Have fun — cried.bio is built to be deeply customizable.",
    ],
  },
];

export function tourPathMatches(pathname: string, href: string): boolean {
  if (href === "/dashboard") return pathname === "/dashboard";
  return pathname === href || pathname.startsWith(`${href}/`);
}
